### ISSUE TITLE
SKU Create File não funciona

### ISSUE THREAD

**Issue by caioinova** [vtex/openapi-schemas#293]
Estou tentando utilizar o exemplo disponível em [https://developers.vtex.com/reference/catalog-api-sku-file#catalog-api-post-sku-file](https://developers.vtex.com/reference/catalog-api-sku-file#catalog-api-post-sku-file)  para criar uma nova imagem para um produto mas esse endpoint parece não estar funcionando. Poderiam corrigir ou me dizer o que estou fazendo de errado nesse caso?

Eu já confirmei que minhas credenciais estão OK (consigo fazer um GET nessa mesma API para listar as imagens desse SKU) e tentei fazer tanto através da URL quanto no meu postman recriando passo-a-passo, mas o resultado é sempre o mesmo (400 Bad Request - Parameter is not valid):

Request body:
`{
    IsMain: false,
    Label: 'label',
    Name: 'prod-bottle',
    Url: 'https://intellihub.s3.us-east-2.amazonaws.com/testobjs/07891150060883.jpg',
    Text: 'product-bottle'
  }`

Response body:
`{
    "Message": "Parameter is not valid."
}`

Response header:
access-control-allow-origin: *
cache-control: no-cache
connection: keep-alive
content-length: 37
content-type: application/json; charset=utf-8
date: Fri, 09 Oct 2020 00:08:40 GMT
expires: -1
pragma: no-cache
server: Microsoft-IIS/10.0
x-aspnet-version: 4.0.30319
x-powered-by: ASP.NET
x-vtex-janus-router-backend-app: ctgapi-vv1.16.42+263

**Comment by htadashi** [comment]
Olá @caioinova, testei aqui e não consegui reproduzir o bug. Para dúvidas sobre a API favor consultar nossa [comunidade de desenvolvedores](https://community.vtex.com/) :)
