### ISSUE TITLE
Missing Catalog Seller Portal Get Products List API documentation

### ISSUE THREAD

**Issue by alexminza** [vtex/openapi-schemas#738]
Previous version named CatalogV2 had the Get Products List method which returned all the products from the seller account with pagination - old URL https://developers.vtex.com/vtex-rest-api/reference/list

This method allowed for scenarios of quickly indexing the Seller Portal CatalogV2 products for the purpose of mapping the products to the Marketplace CatalogV1 - see project https://github.com/vtex-apps/seller-send-offers and specifically:

- https://github.com/vtex-apps/seller-send-offers/blob/master/node/clients/catalogv2.ts#L16
- https://github.com/ElefantOnlineSA/seller-send-offers/blob/MKTP-547/node/clients/catalogv2.ts#L27

Reference: https://github.com/vtex/openapi-schemas/pull/637

**Comment by alexminza** [comment]
CC @julia-rabello

**Comment by julia-rabello** [comment]
I'm closing this issue for now because this route was removed when the Catalog Seller Portal API routes were launched (general availability). I have asked the product team for more context about this decision and, if necessary, I will reopen the issue and update the API reference.

**Comment by alexminza** [comment]
@julia-rabello thank you for the information - where can we provide feedback to the Catalog Seller Portal API team?
