### ISSUE TITLE
Broken Catalog Seller Portal Get Product by external ID, SKU ID, SKU external ID or slug link

### ISSUE THREAD

**Issue by alexminza** [vtex/openapi-schemas#739]
On the [Catalog Seller Portal API](https://developers.vtex.com/docs/api-reference/catalog-api-seller-portal#overview) reference page the link to the [Get Product by external ID, SKU ID, SKU external ID or slug](https://developers.vtex.com/docs/api-reference/catalog-api-seller-portal#get-/api/catalog-seller-portal/products/-param-) method is broken.

However, the documentation is present in the `VTEX - Catalog API Seller Portal.json` file https://github.com/vtex/openapi-schemas/blob/master/VTEX%20-%20Catalog%20API%20Seller%20Portal.json#L1352

Reference: https://github.com/vtex/openapi-schemas/pull/637

**Comment by alexminza** [comment]
CC @julia-rabello

**Comment by julia-rabello** [comment]
Thanks for letting us know, @alexminza! I have fixed the page.
